plugins {
    id 'com.android.application'
}

android {
    namespace 'ar.salem.prueba'
    compileSdk 36
    defaultConfig {
        applicationId "ar.salem.prueba"
        minSdk 24
        targetSdk 36
        versionCode 10
        versionName "0.3.6"
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'androidx.core:core:1.15.0'
}
